# API endpoints
api.download-url=/formula/index/getIndexRequestFile
api.success-url=/formula/pricing/getCalcResult
api.error-url=/formula/pricing/getBatchErrorLog
api.progress-url=/formula/pricing/queryBatchJobStatus
api.new-taskid-url=/formula/pricing/calcBondValuation

# File download path
file.download-path=/downloads

#api.download-url=http://22.22.13.37:8088/formula/index/getIndexRequestFile
#api.success-url=http://22.22.13.37:8088/formula/pricing/getCalcResult
#api.error-url=http://22.22.13.37:8088/formula/pricing/getBatchErrorLog
#api.progress-url=http://22.22.13.37:8088/formula/pricing/queryBatchJobStatus
#api.new-taskid-url=http://22.22.13.37:8088/formula/pricing/calcBondValuation
#
## File download path
#file.download-path=/downloads
